### ISSUE TITLE
Usage Example?

### ISSUE THREAD

**Issue by HughxDev** [Phyks/Blueprinting#1]
In README under “Usage”, it says to “edit it to do something useful”. Could you give an example please? Perhaps something simple like saving the list of installed packages to a text file? I am not a Python coder so the supposed convenience of downloading scripts is being defeated by how much research and configuration I now have to do to make use of them.

**Comment by Phyks** [comment]
This repo was a quick and dirty script to handle a particular use case. I actually do not use it anymore and leave it there in case anyone would build something on top of it. Then, it is mainly targeted to Python dev. It is not really usable in production.

Basically, if you go to https://github.com/Phyks/Blueprinting/blob/master/blueprinting.py, you see some list variables are set, containing the list of packages, the list of aur_packages, the list of modified config files and the list of new config files.

You can do whatever you want with this stuff afterwards. For instance, you can `print()` those variables, or write them to a file (`with open("packages", "w") as fh: fh.write(packages)`).

My idea at the beginning was to be able to store a blueprint of my configuration to replicate it easily (installed packages, aur installed packages and modified config files). After some extra reflexion, I no longer think this is the best way to do. Configuration should be saved as a whole, and we should not keep only the modified configuration files. And in real life use case, things like Ansible should be more reliable and better.

I still see two use cases for this script:
- Help to blueprint a system and it can then be used as a tool to generate Ansible templates from an already installed Arch system.
- Use it as a base block (library) to list modified config files and so on, in a wider script.
